version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run: dotnet build dotnetcore-git-submodule-sample/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
